import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { getServerSession } from "next-auth";
import { authOptions } from "@/app/api/auth/[...nextauth]/options";
import React, { ReactNode } from "react";
import Provider from "@/context/provider";
import { ToastContainer } from "react-toastify";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Fitness app",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: ReactNode;
}) {
  const session = await getServerSession(authOptions);
  if (!session) return <html></html>;
  else if (session) {
    const role = session?.user?.role;

    return (
      <html lang="en">
        <body className={inter.className}>
          <div></div>
          <header
            className="bg-gradient-to-r from-green-400 to-blue-500 flex justify-center items-center"
            style={{ height: "2.5rem" }}
          >
            <Link
              className="mx-2 p-4 text-black font-semibold hover:text-white"
              href={"/dashboard/{role}"}
              as={`/dashboard/${role?.toLowerCase()}`}
            >
              Dashboard ({role})
            </Link>
            <Link
              className="mx-2 p-4 text-black font-semibold hover:text-white"
              href={"/"}
            >
              Home
            </Link>
          </header>

          <main className="flex min-h-screen flex-col items-center p-4">
            <Provider session={session}>
              <ToastContainer />
              {children}
            </Provider>
          </main>
          <nav className="flex justify-between bg-blue-500">
            <Link
              className="mx-2 p-4 text-black font-semibold hover:text-white"
              href={"/api/auth/signout"}
            >
              Logout
            </Link>
          </nav>
        </body>
      </html>
    );
  }
}
