import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { getServerSession } from "next-auth";
import { authOptions } from "@/app/api/auth/[...nextauth]/options";
import React, { ReactNode } from "react";
import Provider from "@/context/provider";
import { ToastContainer } from "react-toastify";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Fitness app",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: ReactNode;
}) {
  const session = await getServerSession(authOptions);
  if (!session) return <html></html>;
  else if (session) {
    const role = session?.user?.role;

    return (
      <html lang="en">
        <body className={inter.className}>
          <div></div>
          <header className="bg-green-100 flex justify-center item-center">
            <Link
              className="mx-2 p-4 text-black font-semibold hover:text-white"
              href={"/"}
            >
              Home
            </Link>
          </header>

          <main className="flex min-h-screen flex-col items-center">
            <Provider session={session}>{children}</Provider>
          </main>
          <nav className="flex justify-between bg-green-100">
            <Link
              className="mx-2 p-4 font-semibold text-black"
              href={"/api/auth/signout"}
            >
              Logout
            </Link>
          </nav>
        </body>
      </html>
    );
  }
}
