import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="flex">
          <Link className="mx-2 p-4" href={"profile"}>
            My profile
          </Link>
          <Link className="mx-2 p-4" href={"dashboard"}>
            Dashboard
          </Link>
        </nav>
        <main className="flex min-h-screen flex-col items-center p-4">
          {children}
        </main>
      </body>
    </html>
  );
}
